### ISSUE TITLE
Use bundle resources instead of #file

### ISSUE THREAD

**Issue by john-mueller** [john-mueller/Hyphenation#2]
Use a resources bundle for default pattern and exception files, instead of lookup using `#file`.

[SE-0271: Package Manager Resources](https://forums.swift.org/t/se-0271-package-manager-resources/30730/72) is expected to be part of the Swift 5.3 release.

**Comment by jeppson57** [comment]
With the Swift 5.3 release now out is there any plan on updating this soon by chance? It works well for us in simulators but crashes on use with the default english patterns.

**Comment by john-mueller** [comment]
I haven't had much time for OSS this past year, but I've been meaning to come back to this recently, so I'll take another look at it.

**Comment by KlemensStrasser** [comment]
@john-mueller Awesome, thank you! 🥳
